// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAECs0DQ6DiWlFDoDbylrB5TGFFFNwk3Q',
    appId: '1:423684973673:web:018e0c832bdb63f61e2ef8',
    messagingSenderId: '423684973673',
    projectId: 'testcarbon-1cbc1',
    authDomain: 'testcarbon-1cbc1.firebaseapp.com',
    storageBucket: 'testcarbon-1cbc1.firebasestorage.app',
    measurementId: 'G-42M7FC03HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LlElJDp-LvTq0bQYiG67WMSPTkFdV8A',
    appId: '1:423684973673:android:5658b2509d1fb4f41e2ef8',
    messagingSenderId: '423684973673',
    projectId: 'testcarbon-1cbc1',
    storageBucket: 'testcarbon-1cbc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxHc2cUL0espjmxAKyXa4r86xJuOnEtas',
    appId: '1:423684973673:ios:b39565991afc72fd1e2ef8',
    messagingSenderId: '423684973673',
    projectId: 'testcarbon-1cbc1',
    storageBucket: 'testcarbon-1cbc1.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxHc2cUL0espjmxAKyXa4r86xJuOnEtas',
    appId: '1:423684973673:ios:b39565991afc72fd1e2ef8',
    messagingSenderId: '423684973673',
    projectId: 'testcarbon-1cbc1',
    storageBucket: 'testcarbon-1cbc1.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAECs0DQ6DiWlFDoDbylrB5TGFFFNwk3Q',
    appId: '1:423684973673:web:8fe89b92c99f2a7b1e2ef8',
    messagingSenderId: '423684973673',
    projectId: 'testcarbon-1cbc1',
    authDomain: 'testcarbon-1cbc1.firebaseapp.com',
    storageBucket: 'testcarbon-1cbc1.firebasestorage.app',
    measurementId: 'G-4HH2F3YSGX',
  );

}