// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLclYo_k9qvkv3h-2WczKx3tJxz4m2t6U',
    appId: '1:610320224091:web:4a32d9ceb042fba733d47e',
    messagingSenderId: '610320224091',
    projectId: 'carbonmobileapp-e6dc3',
    authDomain: 'carbonmobileapp-e6dc3.firebaseapp.com',
    storageBucket: 'carbonmobileapp-e6dc3.firebasestorage.app',
    measurementId: 'G-MYP89HKQ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIaHTjf2HkWF4SN-t0VBid0eU6oIrupBI',
    appId: '1:610320224091:android:0911472b4a49e0fc33d47e',
    messagingSenderId: '610320224091',
    projectId: 'carbonmobileapp-e6dc3',
    storageBucket: 'carbonmobileapp-e6dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ShQfdLcwNRja5wCy9R21oCioRF1Ryd8',
    appId: '1:610320224091:ios:743a37f0f37352b633d47e',
    messagingSenderId: '610320224091',
    projectId: 'carbonmobileapp-e6dc3',
    storageBucket: 'carbonmobileapp-e6dc3.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ShQfdLcwNRja5wCy9R21oCioRF1Ryd8',
    appId: '1:610320224091:ios:743a37f0f37352b633d47e',
    messagingSenderId: '610320224091',
    projectId: 'carbonmobileapp-e6dc3',
    storageBucket: 'carbonmobileapp-e6dc3.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLclYo_k9qvkv3h-2WczKx3tJxz4m2t6U',
    appId: '1:610320224091:web:1171b5650c802cd833d47e',
    messagingSenderId: '610320224091',
    projectId: 'carbonmobileapp-e6dc3',
    authDomain: 'carbonmobileapp-e6dc3.firebaseapp.com',
    storageBucket: 'carbonmobileapp-e6dc3.firebasestorage.app',
    measurementId: 'G-0GRK3Y2ERK',
  );
}
